const Docdata = [
    {
        key:1,
        name:"Dr. Sanjay Ghuge( MBBS , MD)",
        time:"9am - 5pm",
        address:"Cidco, Sukhaharta mindcare clinic, Aurangabad",
        pno:"+091-4448135159",
    },
     {
        key:2,
        name:"Dr. Rajesh Ingole(MBBS MD(psychiatrist))",
        time:"9am – 5pm",
        address:"Housing society , Ambajogai ",
        pno:"+91-2446249955",
    },
     {
        key:3,
        name:"Dr.Shrinivas gupta (MBBS)",
        time:"9am – 5pm",
        address:"Garkheda , Aurangabd",
        pno:"+91-2048553433",
    },
    {
        key:4,
        name:"Dr. rashmin Achlia(MBBS, MD)",
        time:"9am -5pm",
        address:"Kranti chowk , Aurangabad",
        pno:"+91-2071177239",
    },
    {
        key:5,
        name:"Dr. Tejas Gayal(MBBS, DNB-psychiatrist)",
        time:"3 days a week",
        address:"Jai vishwa bharati colony , Aurangabd",
        pno:"+91-2248933646",
    },
    {
        key:6,
        name:" Dr. rachana pole(diploma in psychiatry)",
        time:"9am – 5pm",
        address:"Garkheda , Aurnagbad",
        pno:"+91-2071177239",
    },
    {
        key:7,
        name:"Dr. Meraj Quadri",
        time:"9am – 5pm",
        address:"Padegaon , Aurangabd",
        pno:"+91-2248932501",
    },
    {
        key:8,
        name:"Dr. bhushan Mhetre",
        time:"9am – 5pm",
        address:"Warje, Pune ",
        pno:"+91-2071177324",
    },
    {
        key:9,
        name:"Dr.Rishikesh behere(Neuropsychiatrist , psychotherapist)",
        time:"9am – 5pm",
        address:"Baner Area, Pune ",
        pno:"+91-8037296649",
    },
    {
        key:10,
        name:"Dr. Yogesh Pokale(psychiatrist , Diploma in psychiatry)",
        time:"9am – 5pm",
        address:"Bhosari, pune ",
        pno:"+91-8037298996",
    },
    {
        key:11,
        name:"Disha parikh(psychiatrist )",
        time:"9am – 5pm",
        address:"Baner , Pune",
        pno:"+91-1142246455",
    },
    {
        key:12,
        name:"Dr Pankaj b borade ",
        time:"9am – 5pm",
        address:"Camp area , pune",
        pno:"+91-2071172728",
    },
    {
        key:13,
        name:"Dr . bhushan chaudhari ",
        time:"9am – 5pm",
        address:"Camp area , pune",
        pno:"+91-2071172728",
    },
    {
        key:14,
        name:"Ms. Manisha Bhusa",
        time:"9am – 5pm",
        address:"Ambajogai",
        pno:"86687 07772",
    },
    {
        key:15,
        name:"Mr. Sanjay Chacharkar",
        time:"9am – 5pm",
        address:"US",
        pno:"+1 973-452-2122",
    },
    {
        key:16,
        name:"Mr.Kapil Sir",
        time:"9am – 5pm",
        address:"Ambajogai",
        pno:"+91 98104 28849",
    },
    
];
export default Docdata;